#fichier contenant les valeurs pouvant être modifiées aisément, en particulier les potentiels paramètres

[DEFAULT]
traveler_per_day = 45000
defect_per_day = 1

[INTERFACE]
a = 2
selected_color = #00FF00
# capsule
capsule_width = 20
capsule_height = 20
capsule_outline_width = 1
capsule_color = red
# loop
loop_color = #a0a0a0
# 300 * 3.14 
loop_circumference = 942 
loop_outline_width = 4

# station
station_width = 50
station_height = 50
station_outline_width = 3
station_color = blue

# switch
switch_width = 50
switch_height = 50
switch_outline_width = 3
switch_color = blue

station_size = 

[MODEL]
network_file = /resources/mini_network.json
neutral_percent = 0
activity_and_residential_percent = 30
city_percent = 40
activity_and_residential_fluctuation = 20
morning_peak_hour = 8
evening_peak_hour = 18

[CAPSULE]
velocity = 0
#acceleration = 0
security_distance = 5000  # millimeters
release_time = 12345  # miilisec
acceleration_time = 12345  # miilisec
max_speed = 22.2  # m/s (80km/h)
climbing_time = 8

[ROUTING]
timer_other = 60
my_timer = 40
switched_cost = 100

[SIM]
#Possible values for real_time : True, true, false, False. Otherwise the default value is true
real_time = false
duration = 240
tick = 0.05
start_hour = 8



