[DEFAULT]
traveler_per_day = 45000

[INTERFACE]

[MODEL]
network_file = ../resources/mini_network.json

[CAPSULE]
velocity = 0
#acceleration = 0
security_distance = 5000  # millimeters
release_time = 12345  # miilisec
acceleration_time = 12345  # miilisec
max_speed = 22.2  # m/s (80km/h)

[ROUTING]
timer_other = 60
my_timer = 40
switched_cost = 100

[SIM]
duration = 60
tick = 0.05
start_hour = 12



