[DEFAULT]
traveler_per_day = 45000
defect_per_day = 1

[INTERFACE]

[MODEL]
neutral_percent = 0
activity_and_residential_percent = 30
city_percent = 40
activity_and_residential_fluctuation = 20

[CAPSULE]
velocity = 0
#acceleration = 0
security_distance = 5000  # millimeters
release_time = 12345  # miilisec
acceleration_time = 12345  # miilisec
max_speed = 22.2  # m/s (80km/h)

[ROUTING]
timer_other = 60
my_timer = 40
switched_cost = 100

[SIM]
duration = 60
tick = 0.05
start_hour = 12



