[DEFAULT]
travelers_per_day=4500
# -1 = No limit
trip_limit=-1
traveler_limit=-1
number_of_capsules = -1

[MODEL]
network_file = /resources/mini_network.json
activity_and_residential_percent=30
city_percent=40
activity_and_residential_fluctuation=20
morning_peak_hour=8
evening_peak_hour=18

[CAPSULE]
max_speed=22.23
# m/s (80km/h)
ascent_descent_duration=8

[ROUTING]
timer_other=60
my_timer=40
switched_cost=100

[SIM]
#Possible values for endless : True, true, false, False. Otherwise the default value is false
endless=True
#Possible values for real_time : True, true, false, False. Otherwise the default value is false
real_time=False
duration=300
# Default tick value = 0.05
tick=0.05
start_hour=8
