#fichier contenant les valeurs pouvant être modifiées aisément, en particulier les potentiels paramètres

[DEFAULT]
travelers_per_day = 45000
# defect_per_day = 1
# -1 = No limit
trip_limit = 1
traveler_limit = 1

[INTERFACE]
# a = 2 #TODO a retirer
selected_color = #00FF00
# capsule
capsule_width = 10
capsule_height = 10
capsule_outline_width = 1
capsule_color = red
# loop
loop_color = #a0a0a0
# 300 * 3.14 
loop_circumference = 942
loop_outline_width = 4

# station
station_width = 40
station_height = 40
station_outline_width = 3
station_color = blue

# switch
switch_width = 40
switch_height = 40
switch_outline_width = 3
switch_color = red

station_size =

[MODEL]
network_file = /resources/mini_network.json
activity_and_residential_percent = 30
city_percent = 40
activity_and_residential_fluctuation = 20
morning_peak_hour = 8
evening_peak_hour = 18

[CAPSULE]
# velocity = 0
# acceleration = 0
# security_distance = 5000
# release_time = 12345
# acceleration_time = 12345
# m/s (80km/h)
max_speed = 22.2
ascent_descent_duration = 8

[ROUTING]
timer_other = 60
my_timer = 40
switched_cost = 100

[SIM]
#Possible values for endless : True, true, false, False. Otherwise the default value is false
endless = true
#Possible values for recorded : True, true, false, False. Otherwise the default value is false
#Enable the record when using graphic interface, otherwise disable it
recorded = false
#Possible values for real_time : True, true, false, False. Otherwise the default value is true
real_time = false
duration = -1
# Default tick value = 0.05
tick = 0.05
start_hour = 1
default_record_size = 300



